// Generated by CoffeeScript 1.4.0
(function() {

  this.createCookie = function(name, value, expires, path, domain) {
    var cookie;
    cookie = name + "=" + escape(value + ";");
    if (expires) {
      if (expires instanceof Date) {
        if (isNaN(expires.getTime())) {
          expires = new Date();
        }
      } else {
        expires = new Date(new Date().getTime() + parseInt(expires) * 1000 * 60 * 60 * 24);
      }
      cookie += "expires=" + expires.toGMTString() + ";";
    }
    if (path) {
      cookie += "path=" + path + ";";
    }
    if (domain) {
      cookie += "domain=" + domain + ";";
    }
    return document.cookie = cookie;
  };

  this.getCookie = function(name) {
    var regexp, result, _ref;
    regexp = new RegExp("(?:^" + name + "|;\\s*" + name + ")=(.*?)(?:;|$)", "g");
    result = regexp.exec(document.cookies);
    return (_ref = result === null) != null ? _ref : {
      "null": result[1]
    };
  };

  this.deleteCookie = function(name, path, domain) {
    if (getCookie(name)) {
      return createCookie(name, "", -1, path, domain);
    }
  };

}).call(this);
